apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: Cluster platform and infrastructure components
  sourceRepos:
    - https://github.com/rbomfimpro/gitops-owl-v2.git
    - https://github.com/rbomfimpro/k8s-apps-v3.git
    - https://grafana-community.github.io/helm-charts/
    - https://ui.charts.kafbat.io/
    - https://prometheus-community.github.io/helm-charts
    - oci://ghcr.io/argoproj/argo-helm/argo-cd
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"