apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Cluster platform and infrastructure components
  sourceRepos:
    - https://github.com/rbomfimpro/gitops-owl-v2.git
    - https://github.com/rbomfimpro/k8s-apps-v3.git
    - https://grafana-community.github.io/helm-charts/
  destinations:
    - server: https://kubernetes.default.svc
      namespace: platform
    - server: https://kubernetes.default.svc
      namespace: monitoring