apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Company application workloads
  sourceRepos:
    - https://github.com/rbomfimpro/gitops-owl-v2.git
    - https://github.com/rbomfimpro/k8s-apps-v3.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: apps
  syncWindows:
    - kind: allow
      timeZone: "America/Sao_Paulo"
      schedule: '0 8 * * 1-5'
      duration: 14h
  namespaceResourceWhitelist:
    # core
    - group: ""
      kind: "ConfigMap"
    - group: ""
      kind: "Secret"
    - group: ""
      kind: "Service"
    - group: ""
      kind: "ServiceAccount"
    - group: ""
      kind: "PersistentVolumeClaim"
    # apps
    - group: "apps"
      kind: "DaemonSet"
    - group: "apps"
      kind: "Deployment"
    - group: "apps"
      kind: "StatefulSet"
    # batch
    - group: "batch"
      kind: "Job"
    - group: "batch"
      kind: "CronJob"
    # scaling and distribution
    - group: "autoscaling"
      kind: "HorizontalPodAutoscaler"
    - group: "policy"
      kind: "PodDisruptionBudget"
    # networking
    - group: "gateway.networking.k8s.io"
      kind: "GRPCRoute"
    - group: "gateway.networking.k8s.io"
      kind: "HTTPRoute"
    - group: "networking.k8s.io"
      kind: "Ingress"