apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/argoproj/argo-helm/argo-cd
      targetRevision: 9.5.17
      path: .
      helm:
        releaseName: argocd
      valueFiles:
      - $values/manifests/argocd/values.yaml
    - repoURL: https://github.com/rbomfimpro/gitops-owl-v2
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd