apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: 2.41.0
      helm:
        releaseName: argo-rollouts
        valueFiles:
          - $values/manifests/argo-rollouts/values.yaml
    - repoURL: https://github.com/rbomfimpro/gitops-owl
      targetRevision: main
      ref: values
      path: manifests/argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: platform