apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts/
      chart: grafana
      targetRevision: 12.4.8
      helm:
        releaseName: grafana
        valueFiles:
          - $values/manifests/grafana/values.yaml
    - repoURL: https://github.com/rbomfimpro/gitops-owl
      targetRevision: main
      ref: values
      path: manifests/grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring