apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://ui.charts.kafbat.io/
      chart: kafka-ui
      targetRevision: 1.6.4
      helm:
        releaseName: kafka-ui
        valueFiles:
          - $values/manifests/kafka-ui/values.yaml
    - repoURL: https://github.com/rbomfimpro/gitops-owl
      targetRevision: main
      ref: values
      path: manifests/kafka-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: platform