apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  labels:
    version: 6.10.0
spec:
  project: workloads
  source:
    repoURL: https://github.com/rbomfimpro/gitops-owl
    targetRevision: main
    path: manifests/podinfo
    kustomize:
      images:
        - ghcr.io/stefanprodan/podinfo:6.10.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: apps