apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 29.9.0
      helm:
        releaseName: prometheus
        valuesFiles:
          - $values/manifests/prometheus/values.yaml
    - repoURL: https://github.com/rbomfimpro/gitops-owl-v2
      targetRevision: main
      ref: values
    - repoURL: https://github.com/rbomfimpro/gitops-owl-v2
      targetRevision: main
      path: manifests/prometheus/extras
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
