apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 29.9.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/manifests/prometheus/values.yaml
    - repoURL: https://github.com/rbomfimpro/gitops-owl
      targetRevision: main
      ref: values
      path: manifests/prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring