apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/argoproj/argo-helm
      chart: argo-cd
      targetRevision: 9.4.10
      helm:
        releaseName: argocd
        valueFiles:
          - $values/argocd/values.yaml
    - repoURL: https://github.com/rbomfimpro/gitops-owl.git
      targetRevision: HEAD
      path: applications/infra
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd