apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rbomfimpro/gitops-owl.git
    targetRevision: HEAD
    path: applications/workloads/chaos
  destination:
    server: https://kubernetes.default.svc
    namespace: workloads
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true