apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quotas
  namespace: apps
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "6"
    limits.memory: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: apps
spec:
  limits:
    - type: Pod
      min:
        cpu: 10m
        memory: 16Mi
      max:
        cpu: 1
        memory: 1Gi
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 16Mi
