apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://emberstack.github.io/helm-charts
      chart: reflector
      targetRevision: 10.0.17
      helm:
        releaseName: reflector
  destination:
    server: https://kubernetes.default.svc
    namespace: core